local harpoon = require("harpoon")
harpoon:setup({})

vim.keymap.set("n", "<c-a>", function()
	harpoon:list():add()
end, { desc = "add harpoon" })
vim.keymap.set("n", "<C-e>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "󰍜 Quick Menu Harpoon" })

vim.keymap.set("n", "<C-h>", function()
	harpoon:list():select(1)
end, { desc = "󰛢1" })
vim.keymap.set("n", "<C-t>", function()
	harpoon:list():select(2)
end, { desc = "󰛢2" })
vim.keymap.set("n", "<C-n>", function()
	harpoon:list():select(3)
end, { desc = "󰛢3" })
vim.keymap.set("n", "<C-s>", function()
	harpoon:list():select(4)
end, { desc = "󰛢4" })

-- Toggle previous & next buffers stored within Harpoon list
vim.keymap.set("n", "<leader>hp", function()
	harpoon:list():prev()
end, { desc = "󰛢Next" })
vim.keymap.set("n", "<leader>hn", function()
	harpoon:list():next()
end, { desc = "󰛢Prev" })
