vim.keymap.set("n", "<Tab>", vim.cmd.bnext)
vim.keymap.set("n", "<S-Tab>", vim.cmd.bprevious)
vim.keymap.set("n", "<leader>o", "o<Esc>k")
vim.keymap.set("n", "<leader>x", vim.cmd.dbelete)
vim.keymap.set("n", "<leader>y", '"+yy', { noremap = true })
vim.keymap.set("n", "<leader>dy", "3<cmd>lua vim.diagnostic.open_float()<CR>", { noremap = true })
vim.keymap.set("n", "<leader>fi", "/", { noremap = true })
vim.keymap.set("n", "<leader>a", "ggVG", { noremap = true })
